# Generated by Django 4.0 on 2021-12-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(null=True),
        ),
    ]
