# Generated by Django 4.0 on 2021-12-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs_list', '0003_artist_alter_song_youtube_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs_list.artist'),
        ),
    ]
